import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer/Footer'
import NavBar from '../components/NavBar/NavBar'
import Products from '../components/Products/Products'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My First NextJS App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <Products />
        <Footer />
      </main>

    </div>
  )
}
